

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - workhub_network

  app:
    image: workhub.azurecr.io/workhub_app
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      MSAL_TENANT_ID: ${MSAL_TENANT_ID}
      MSAL_CLIENT_ID: ${MSAL_CLIENT_ID}
      MSAL_REDIRECT_URI: ${MSAL_REDIRECT_URI}
      MSAL_CLIENT_SECRET: ${MSAL_CLIENT_SECRET}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPORT: ${PGPORT}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
    ports:
      - "9000:9000"
    networks:
      - workhub_network

  frontend:
    image: workhub.azurecr.io/workhub_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_MSAL_TENANT_ID: ${NEXT_PUBLIC_MSAL_TENANT_ID}
      NEXT_PUBLIC_MSAL_CLIENT_ID: ${NEXT_PUBLIC_MSAL_CLIENT_ID}
      NEXT_PUBLIC_MSAL_REDIRECT_URI: ${NEXT_PUBLIC_MSAL_REDIRECT_URI}
      NEXT_PUBLIC_MSAL_CLIENT_SECRET: ${NEXT_PUBLIC_MSAL_CLIENT_SECRET}
      DJANGO_API_BASE_URL: ${DJANGO_API_BASE_URL}
    networks:
      - workhub_network

  celery:
    image: workhub.azurecr.io/workhub_celery
    command: >
      celery -A IBOS worker
      -l INFO
      --concurrency=1
      --prefetch-multiplier=1
      --max-tasks-per-child=10
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - workhub_network

  celery_beat:
    image: workhub.azurecr.io/workhub_celery_beat
    command: celery -A IBOS beat -l INFO
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - workhub_network

  proxy:
    image: workhub.azurecr.io/workhub_proxy
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
    networks:
      - workhub_network

networks:
  workhub_network:

volumes:
  static-data:
